package com.gmb.bbm2.data.model;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "BBM_STATEMENT".
 */
public class BbmStatementFB {

    private String id;
    private String nom;
    private String nomsystem;
    private String descrip;
    private String type;
    private String sens;
    private Boolean recurring;
    private Boolean isautomaticpay;
    private Integer qnte;
    private Double pu;
    private Double montant;
    private String url;
    private Long datestart;
    private Long timestart;
    private Long dateend;
    private Long timeend;
    private Boolean unlimited;
    private String typeend;
    private String repeatunit;
    private Integer repeatfreq;
    private Integer nbrerepeat;
    private String currentstate;
    private String reminderconf;
    private String daysofweek;
    private Integer dayofweekormonth;
    private Integer dayweekinmonth;
    private String idcat;

    /** Used to resolve relations */



    public BbmStatementFB() {
    }

    public BbmStatementFB(String id) {
        this.id = id;
    }

    public BbmStatementFB(String id, String nom, String nomsystem, String descrip, String type, String sens, Boolean recurring,
                          Boolean isautomaticpay, Integer qnte, Double pu, Double montant, String url, Long datestart, Long timestart,
                          Long dateend, Long timeend, Boolean unlimited, String typeend, String repeatunit, Integer repeatfreq,
                          Integer nbrerepeat, String currentstate, String reminderconf, String daysofweek, Integer dayofweekormonth, Integer dayweekinmonth, String idcat) {
        this.id = id;
        this.nom = nom;
        this.nomsystem = nomsystem;
        this.descrip = descrip;
        this.type = type;
        this.sens = sens;
        this.recurring = recurring;
        this.isautomaticpay = isautomaticpay;
        this.qnte = qnte;
        this.pu = pu;
        this.montant = montant;
        this.url = url;
        this.datestart = datestart;
        this.timestart = timestart;
        this.dateend = dateend;
        this.timeend = timeend;
        this.unlimited = unlimited;
        this.typeend = typeend;
        this.repeatunit = repeatunit;
        this.repeatfreq = repeatfreq;
        this.nbrerepeat = nbrerepeat;
        this.currentstate = currentstate;
        this.reminderconf = reminderconf;
        this.daysofweek = daysofweek;
        this.dayofweekormonth = dayofweekormonth;
        this.dayweekinmonth = dayweekinmonth;
        this.idcat = idcat;
    }



    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getNomsystem() {
        return nomsystem;
    }

    public void setNomsystem(String nomsystem) {
        this.nomsystem = nomsystem;
    }

    public String getDescrip() {
        return descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSens() {
        return sens;
    }

    public void setSens(String sens) {
        this.sens = sens;
    }

    public Boolean getRecurring() {
        return recurring;
    }

    public void setRecurring(Boolean recurring) {
        this.recurring = recurring;
    }

    public Boolean getIsautomaticpay() {
        return isautomaticpay;
    }

    public void setIsautomaticpay(Boolean isautomaticpay) {
        this.isautomaticpay = isautomaticpay;
    }

    public Integer getQnte() {
        return qnte;
    }

    public void setQnte(Integer qnte) {
        this.qnte = qnte;
    }

    public Double getPu() {
        return pu;
    }

    public void setPu(Double pu) {
        this.pu = pu;
    }

    public Double getMontant() {
        return montant;
    }

    public void setMontant(Double montant) {
        this.montant = montant;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getDatestart() {
        return datestart;
    }

    public void setDatestart(Long datestart) {
        this.datestart = datestart;
    }

    public Long getTimestart() {
        return timestart;
    }

    public void setTimestart(Long timestart) {
        this.timestart = timestart;
    }

    public Long getDateend() {
        return dateend;
    }

    public void setDateend(Long dateend) {
        this.dateend = dateend;
    }

    public Long getTimeend() {
        return timeend;
    }

    public void setTimeend(Long timeend) {
        this.timeend = timeend;
    }

    public Boolean getUnlimited() {
        return unlimited;
    }

    public void setUnlimited(Boolean unlimited) {
        this.unlimited = unlimited;
    }

    public String getTypeend() {
        return typeend;
    }

    public void setTypeend(String typeend) {
        this.typeend = typeend;
    }

    public String getRepeatunit() {
        return repeatunit;
    }

    public void setRepeatunit(String repeatunit) {
        this.repeatunit = repeatunit;
    }

    public Integer getRepeatfreq() {
        return repeatfreq;
    }

    public void setRepeatfreq(Integer repeatfreq) {
        this.repeatfreq = repeatfreq;
    }

    public Integer getNbrerepeat() {
        return nbrerepeat;
    }

    public void setNbrerepeat(Integer nbrerepeat) {
        this.nbrerepeat = nbrerepeat;
    }

    public String getCurrentstate() {
        return currentstate;
    }

    public void setCurrentstate(String currentstate) {
        this.currentstate = currentstate;
    }

    public String getReminderconf() {
        return reminderconf;
    }

    public void setReminderconf(String reminderconf) {
        this.reminderconf = reminderconf;
    }

    public String getDaysofweek() {
        return daysofweek;
    }

    public void setDaysofweek(String daysofweek) {
        this.daysofweek = daysofweek;
    }

    public Integer getDayofweekormonth() {
        return dayofweekormonth;
    }

    public void setDayofweekormonth(Integer dayofweekormonth) {
        this.dayofweekormonth = dayofweekormonth;
    }

    public Integer getDayweekinmonth() {
        return dayweekinmonth;
    }

    public void setDayweekinmonth(Integer dayweekinmonth) {
        this.dayweekinmonth = dayweekinmonth;
    }

    public String getIdcat() {
        return idcat;
    }

    public void setIdcat(String idcat) {
        this.idcat = idcat;
    }



}
