package com.gmb.bbm2.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "BUDGET".
 */
public class BudgetFB {

    private String id;
    private Long datestart;
    private Long dateend;
    private Double montantmax;
    private Double montantprojecte;
    private Double montantreel;
    private String ch1;
    private String ch2;
    private String ch3;
    private String idcat;
    private int month;
    private int year;
    private Long dateLastEdit;




    public BudgetFB() {
    }

    public BudgetFB(String id) {
        this.id = id;
    }

    public BudgetFB(String id, Long datestart, Long dateend, Double montantmax, Double montantprojecte, Double montantreel, String ch1, String ch2, String ch3, String idcat) {
        this.id = id;
        this.datestart = datestart;
        this.dateend = dateend;
        this.montantmax = montantmax;
        this.montantprojecte = montantprojecte;
        this.montantreel = montantreel;
        this.ch1 = ch1;
        this.ch2 = ch2;
        this.ch3 = ch3;
        this.idcat = idcat;
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getDatestart() {
        return datestart;
    }

    public void setDatestart(Long datestart) {
        this.datestart = datestart;
    }

    public Long getDateend() {
        return dateend;
    }

    public void setDateend(Long dateend) {
        this.dateend = dateend;
    }

    public Double getMontantmax() {
        return montantmax;
    }

    public void setMontantmax(Double montantmax) {
        this.montantmax = montantmax;
    }

    public Double getMontantprojecte() {
        return montantprojecte;
    }

    public void setMontantprojecte(Double montantprojecte) {
        this.montantprojecte = montantprojecte;
    }

    public Double getMontantreel() {
        return montantreel;
    }

    public void setMontantreel(Double montantreel) {
        this.montantreel = montantreel;
    }

    public String getCh1() {
        return ch1;
    }

    public void setCh1(String ch1) {
        this.ch1 = ch1;
    }

    public String getCh2() {
        return ch2;
    }

    public void setCh2(String ch2) {
        this.ch2 = ch2;
    }

    public String getCh3() {
        return ch3;
    }

    public void setCh3(String ch3) {
        this.ch3 = ch3;
    }

    public String getIdcat() {
        return idcat;
    }

    public void setIdcat(String idcat) {
        this.idcat = idcat;
    }


}
