package com.gmb.bbm2.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CATEGORY".
 */
public class CategoryFB {

    private String id;
    private String nom;
    private String nomaffiche;
    private Double minamount;
    private Boolean allowoverdue;
    private String ch1;
    private String ch2;
    private String ch3;


    public CategoryFB() {
    }

    public CategoryFB(String id) {
        this.id = id;
    }

    public CategoryFB(String id, String nom, String nomaffiche, Double minamount, Boolean allowoverdue, String ch1, String ch2, String ch3) {
        this.id = id;
        this.nom = nom;
        this.nomaffiche = nomaffiche;
        this.minamount = minamount;
        this.allowoverdue = allowoverdue;
        this.ch1 = ch1;
        this.ch2 = ch2;
        this.ch3 = ch3;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getNomaffiche() {
        return nomaffiche;
    }

    public void setNomaffiche(String nomaffiche) {
        this.nomaffiche = nomaffiche;
    }

    public Double getMinamount() {
        return minamount;
    }

    public void setMinamount(Double minamount) {
        this.minamount = minamount;
    }

    public Boolean getAllowoverdue() {
        return allowoverdue;
    }

    public void setAllowoverdue(Boolean allowoverdue) {
        this.allowoverdue = allowoverdue;
    }

    public String getCh1() {
        return ch1;
    }

    public void setCh1(String ch1) {
        this.ch1 = ch1;
    }

    public String getCh2() {
        return ch2;
    }

    public void setCh2(String ch2) {
        this.ch2 = ch2;
    }

    public String getCh3() {
        return ch3;
    }

    public void setCh3(String ch3) {
        this.ch3 = ch3;
    }


}
