package com.gmb.bbm2.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_SETTINGS".
 */
public class MySettingsFB {

    private String id;
    private String key;
    private String val;
    private Long dateupdate;
    private String ch1;
    private String ch2;

    public MySettingsFB() {
    }

    public MySettingsFB(String id) {
        this.id = id;
    }

    public MySettingsFB(String id, String key, String val, Long dateupdate, String ch1, String ch2) {
        this.id = id;
        this.key = key;
        this.val = val;
        this.dateupdate = dateupdate;
        this.ch1 = ch1;
        this.ch2 = ch2;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }

    public Long getDateupdate() {
        return dateupdate;
    }

    public void setDateupdate(Long dateupdate) {
        this.dateupdate = dateupdate;
    }

    public String getCh1() {
        return ch1;
    }

    public void setCh1(String ch1) {
        this.ch1 = ch1;
    }

    public String getCh2() {
        return ch2;
    }

    public void setCh2(String ch2) {
        this.ch2 = ch2;
    }

}
