package com.gmb.bbm2.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "ON_TIME_NOTIFICATION".
 */
public class OnTimeNotificationFB {

    public final static String FIELD_CURRENT_STATE="currentstate";
    public final static String FIELD_MONTANT_OP="montantop";
    public final static String FIELD_DATE_OP="dateop";
    public final static String FIELD_PAID_OP="paidop";

    private String id;
    private Long datestart;
    private Long timestart;
    private String currentstate;
    private Long dateop;
    private Double puop;
    private Integer qnteop;
    private Double montantop;
    private Double totalop;
    private Boolean paidop;
    private Double montantprojecte;
    private Long dateprojecte;
    private Long datereel;
    private Double penalite;
    private String ch1;
    private String ch2;
    private String ch3;
    private String idstate;
    private String idcat;


    private Boolean isactualnotif;
    private Boolean alarmset;
    private Integer idalarm;


    private String nom;
    private String nomsystem;
    private String descrip;
    private String type;
    private String sens;
    private Boolean recurring;
    private Boolean isautomaticpay;
    private Long timeend;
    private String url;
    private Boolean unlimited;
    private String typeend;
    private String repeatunit;
    private Integer repeatfreq;
    private Integer nbrerepeat;
    private String reminderconf;
    private String daysofweek;
    private Integer dayofweekormonth;
    private Integer dayweekinmonth;

    public OnTimeNotificationFB() {
    }

    public OnTimeNotificationFB(String id) {
        this.id = id;
    }

    public OnTimeNotificationFB(String id, Long datestart, Long timestart, String currentstate, Long dateop, Double puop, Integer qnteop, Double montantop, Double totalop, Boolean paidop, Double montantprojecte,
                                Long dateprojecte, Long datereel, Double penalite, String ch1, String ch2, String ch3, String idstate,String idcat,
                                String nom, String nomsystem, String descrip, String type, String sens, Boolean recurring,
                                Boolean isautomaticpay,String url,Long timeend, Boolean unlimited, String typeend, String repeatunit, Integer repeatfreq,
                                Integer nbrerepeat, String reminderconf, String daysofweek, Integer dayofweekormonth, Integer dayweekinmonth, boolean isActualNotif, boolean alarmset,Integer idalarm) {
        this.id = id;
        this.datestart = datestart;
        this.timestart = timestart;
        this.currentstate = currentstate;
        this.dateop = dateop;
        this.puop = puop;
        this.qnteop = qnteop;
        this.montantop = montantop;
        this.totalop = totalop;
        this.paidop = paidop;
        this.montantprojecte = montantprojecte;
        this.dateprojecte = dateprojecte;
        this.datereel = datereel;
        this.penalite = penalite;
        this.ch1 = ch1;
        this.ch2 = ch2;
        this.ch3 = ch3;
        this.idstate = idstate;
        this.idcat=idcat;


        this.isactualnotif=isActualNotif;
        this.alarmset=alarmset;
        this.idalarm=idalarm;


        this.id = id;
        this.nom = nom;
        this.nomsystem = nomsystem;
        this.descrip = descrip;
        this.type = type;
        this.sens = sens;
        this.recurring = recurring;
        this.isautomaticpay = isautomaticpay;
        this.url = url;
        this.datestart = datestart;
        this.timestart = timestart;
        this.timeend = timeend;
        this.unlimited = unlimited;
        this.typeend = typeend;
        this.repeatunit = repeatunit;
        this.repeatfreq = repeatfreq;
        this.nbrerepeat = nbrerepeat;
        this.currentstate = currentstate;
        this.reminderconf = reminderconf;
        this.daysofweek = daysofweek;
        this.dayofweekormonth = dayofweekormonth;
        this.dayweekinmonth = dayweekinmonth;
        this.idcat = idcat;
    }

    public Boolean getIsactualnotif() {
        return isactualnotif;
    }

    public void setIsactualnotif(Boolean isactualnotif) {
        this.isactualnotif = isactualnotif;
    }

    public Boolean getAlarmset() {
        return alarmset;
    }

    public void setAlarmset(Boolean alarmset) {
        this.alarmset = alarmset;
    }

    public Integer getIdalarm() {
        return idalarm;
    }

    public void setIdalarm(Integer idalarm) {
        this.idalarm = idalarm;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getDatestart() {
        return datestart;
    }

    public void setDatestart(Long datestart) {
        this.datestart = datestart;
    }

    public Long getTimestart() {
        return timestart;
    }

    public void setTimestart(Long timestart) {
        this.timestart = timestart;
    }

    public String getCurrentstate() {
        return currentstate;
    }

    public void setCurrentstate(String currentstate) {
        this.currentstate = currentstate;
    }

    public Long getDateop() {
        return dateop;
    }

    public void setDateop(Long dateop) {
        this.dateop = dateop;
    }

    public Double getPuop() {
        return puop;
    }

    public void setPuop(Double puop) {
        this.puop = puop;
    }

    public Integer getQnteop() {
        return qnteop;
    }

    public void setQnteop(Integer qnteop) {
        this.qnteop = qnteop;
    }

    public Double getMontantop() {
        return montantop;
    }

    public void setMontantop(Double montantop) {
        this.montantop = montantop;
    }

    public Double getTotalop() {
        return totalop;
    }

    public void setTotalop(Double totalop) {
        this.totalop = totalop;
    }

    public Boolean getPaidop() {
        return paidop;
    }

    public void setPaidop(Boolean paidop) {
        this.paidop = paidop;
    }

    public Double getMontantprojecte() {
        return montantprojecte;
    }

    public void setMontantprojecte(Double montantprojecte) {
        this.montantprojecte = montantprojecte;
    }

    public Long getDateprojecte() {
        return dateprojecte;
    }

    public void setDateprojecte(Long dateprojecte) {
        this.dateprojecte = dateprojecte;
    }

    public Long getDatereel() {
        return datereel;
    }

    public void setDatereel(Long datereel) {
        this.datereel = datereel;
    }

    public Double getPenalite() {
        return penalite;
    }

    public void setPenalite(Double penalite) {
        this.penalite = penalite;
    }

    public String getCh1() {
        return ch1;
    }

    public void setCh1(String ch1) {
        this.ch1 = ch1;
    }

    public String getCh2() {
        return ch2;
    }

    public void setCh2(String ch2) {
        this.ch2 = ch2;
    }

    public String getCh3() {
        return ch3;
    }

    public void setCh3(String ch3) {
        this.ch3 = ch3;
    }

    public String getIdstate() {
        return idstate;
    }

    public void setIdstate(String idstate) {
        this.idstate = idstate;
    }

    public String getIdcat() {
        return idcat;
    }

    public void setIdcat(String idcat) {
        this.idcat = idcat;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getNomsystem() {
        return nomsystem;
    }

    public void setNomsystem(String nomsystem) {
        this.nomsystem = nomsystem;
    }

    public String getDescrip() {
        return descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSens() {
        return sens;
    }

    public void setSens(String sens) {
        this.sens = sens;
    }

    public Boolean getRecurring() {
        return recurring;
    }

    public void setRecurring(Boolean recurring) {
        this.recurring = recurring;
    }

    public Boolean getIsautomaticpay() {
        return isautomaticpay;
    }

    public void setIsautomaticpay(Boolean isautomaticpay) {
        this.isautomaticpay = isautomaticpay;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getUnlimited() {
        return unlimited;
    }

    public void setUnlimited(Boolean unlimited) {
        this.unlimited = unlimited;
    }

    public String getTypeend() {
        return typeend;
    }

    public void setTypeend(String typeend) {
        this.typeend = typeend;
    }

    public String getRepeatunit() {
        return repeatunit;
    }

    public void setRepeatunit(String repeatunit) {
        this.repeatunit = repeatunit;
    }

    public Integer getRepeatfreq() {
        return repeatfreq;
    }

    public void setRepeatfreq(Integer repeatfreq) {
        this.repeatfreq = repeatfreq;
    }

    public Integer getNbrerepeat() {
        return nbrerepeat;
    }

    public void setNbrerepeat(Integer nbrerepeat) {
        this.nbrerepeat = nbrerepeat;
    }

    public String getReminderconf() {
        return reminderconf;
    }

    public void setReminderconf(String reminderconf) {
        this.reminderconf = reminderconf;
    }

    public String getDaysofweek() {
        return daysofweek;
    }

    public void setDaysofweek(String daysofweek) {
        this.daysofweek = daysofweek;
    }

    public Integer getDayofweekormonth() {
        return dayofweekormonth;
    }

    public void setDayofweekormonth(Integer dayofweekormonth) {
        this.dayofweekormonth = dayofweekormonth;
    }

    public Integer getDayweekinmonth() {
        return dayweekinmonth;
    }

    public void setDayweekinmonth(Integer dayweekinmonth) {
        this.dayweekinmonth = dayweekinmonth;
    }

    public Long getTimeend() {
        return timeend;
    }

    public void setTimeend(Long timeend) {
        this.timeend = timeend;
    }
}
